quadrantChart
    title Kwadranty testow
    x-axis Technologiczne --> Biznesowe
    y-axis Wspierajace zespol --> Sprawdzajace produkt
    quadrant-1 Produkt biznesowy
    quadrant-2 Produkt technologiczny
    quadrant-3 Wsparcie technologiczne
    quadrant-4 Wsparcie biznesowe
    Testy jednostkowe: [0.2, 0.2]
    Testy wydajnosci: [0.25, 0.8]
    Testy akceptacyjne: [0.8, 0.8]
    Przyk lady akceptacyjne: [0.75, 0.25]
