quadrantChart
    title Kwadrant dlugu technologicznego
    x-axis Niezamierzony --> Zamierzony
    y-axis Lekkomyslny --> Rozwazny
    quadrant-1 Rozwazny zamierzony
    quadrant-2 Rozwazny niezamierzony
    quadrant-3 Lekkomyslny niezamierzony
    quadrant-4 Lekkomyslny zamierzony
    brak testow: [0.8, 0.2]
    nieznany framework: [0.2, 0.2]
    swiadomy MVP: [0.8, 0.8]
    dobry pomysl, zly efekt: [0.2, 0.8]
